title: Teun Zengerink
email: teun@zengerink.com
description: >-
  Teun Zengerink studies photography at the Fotoacademie Amsterdam. After
  finishing his bachelors degree in Arts, Culture & Media, he started
  working in the IT-industry as he's also holding a bachelor in Business
  Administration & Computer Science. The idea of doing something with his
  creativity started to grow on him, which made him explore for ways to
  do so.
url: "http://teun.zengerink.com"

collections:
  work:
    output: true

defaults:
  - scope:
      path: "assets/photos"
    values:
      image: true

sass:
  style: compressed

markdown: kramdown
