title: Teun Zengerink
email: teun@zengerink.com
description: >-
  Teun Zengerink
url: "http://teun.zengerink.com"

collections:
  work:
    output: true

defaults:
  - scope:
      path: "assets/photos"
    values:
      image: true

sass:
  style: compressed

markdown: kramdown
